version: '3.5'

networks:
  freeladev.net.msprojects:
    driver: bridge
  freeladev.net.msprojects.db:
    driver: bridge
  freeladev.net.mspayments:
    driver: bridge
  freeladev.net.mspayments.db:
    driver: bridge
  freeladev.net.broker:
    driver: bridge

services:
  freeladev.msprojects.db:
    image: mysql:latest
    container_name: freeladev.msprojects.db
    networks:
      - freeladev.net.msprojects.db
    ports:
      - 3306:3036
    environment:
      MYSQL_USER: jooba
      MYSQL_PASSWORD: joobasecretandlonsgpassword
      MYSQL_ROOT_PASSWORD: rootsecretandlongpassword
      MYSQL_DATABASE: msprojectsdb
    volumes:
      - /FreelaDev.MsProjects.Infrastructure/Db:/var/lib/mysql
  freeladev.msprojects.api:
    image: freeladev.msprojects.api
    networks:
      - freeladev.net.msprojects
      - freeladev.net.msprojects.db
      - freeladev.net.broker
    build:
      context: .
      dockerfile: FreelaDev.MsProjects.Api/Dockerfile
    container_name: freeladev.msprojects.api
    restart: always
    depends_on: 
      - freeladev.msprojects.db
      - freeladev.broker
    ports:
      - 8080:8080
  freeladev.mspayments.db:
    image: mysql:latest
    container_name: freeladev.mspayments.db
    networks:
      - freeladev.net.mspayments.db
    ports:
      - 3307:3036
    environment:
      MYSQL_USER: jooba
      MYSQL_PASSWORD: joobasecretandlonsgpassword
      MYSQL_ROOT_PASSWORD: rootsecretandlongpassword
      MYSQL_DATABASE: mspaymentsdb
    volumes:
      - /FreelaDev.MsPayments.Infrastructure/Db:/var/lib/mysql
  freeladev.mspayments.api:
    image: freeladev.mspayments.api
    build:
      context: .
      dockerfile: FreelaDev.MsPayments.Api/Dockerfile
    container_name: freeladev.mspayments.api
    restart: always
    networks:
      - freeladev.net.mspayments
      - freeladev.net.mspayments.db
      - freeladev.net.broker
    depends_on: 
      - freeladev.broker
      - freeladev.mspayments.db
    ports:
      - 8081:8080
  freeladev.broker:
    image: rabbitmq:3-management
    container_name: broker
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - freeladev.net.broker
    