PUT http://localhost:8080/api/projects/start
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOGRjMzE0Ni0wYmI2LTQ1MTktODdlMC01OTg4ODMxZWMwNWIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MCwiZXhwIjowLCJpc3MiOiJmcmVlbGFkZXZtc3Byb2plY3RhcGkiLCJhdWQiOiJhZG1pbixmcmVlbGFuY2VyLGNsaWVudCJ9.bW5cGnU3IfqJX-Oxzeg9x9jIK_to2U6w2ybnv4zGkYuoXol9Pu2WMYH_lhEecZ3t3UsDy_BZPahYDPK5tG0qbg
Content-Type: application/json

{
  "idProject": "08dc2fc1-7fc1-4fd1-862b-16e9758ac735"
}
###