POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "José",
  "lastName": "Back",
  "email": "jose@mail.com",
  "password": "123",
  "role": 1,
  "skills": [
    {
      "description": ".NET Core 7+"
    }
  ]
}